import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  console.log("layout !!")

  return (
    <html lang="en">
      {/* <Script
        // strategy="beforeInteractive"
        type="text/javascript"
        src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpClientId=${process.env.NAVER_MAPS_CLIENT_ID}`}
      ></Script> */}
      {/* <div>this is layout com</div> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
